-- Create stats table
create table public.stats (
  id integer generated by default as identity primary key,
  label text not null,
  value text not null,
  icon_name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Enable RLS for stats
alter table public.stats enable row level security;

-- Policies for stats
create policy "Anyone can view stats"
  on public.stats for select
  using (true);

create policy "Admin can update stats"
  on public.stats for update
  using (auth.email() = 'vigneshwarvigneshwar292@gmail.com');

create policy "Admin can insert stats"
  on public.stats for insert
  with check (auth.email() = 'vigneshwarvigneshwar292@gmail.com');

create policy "Admin can delete stats"
  on public.stats for delete
  using (auth.email() = 'vigneshwarvigneshwar292@gmail.com');

-- Insert initial 4 stats
insert into public.stats (id, label, value, icon_name, description) values
  (1, 'Active Members', '500+', 'Users', 'Active Members'),
  (2, 'Events Hosted', '50+', 'Calendar', 'Events Hosted'),
  (3, 'Contest Winners', '120+', 'Trophy', 'Internships Secured'),
  (4, 'Resources', '200+', 'BookOpen', 'Resources Shared');
  
-- Note: 'Contest Winners' is used on Home Page, 'Internships Secured' is used on About Page. 
-- For simplicity, we can use the main label for Home and description for About, or just keep them same.
-- The prompt said "120 contest winners".
