-- Create events table
create table public.events (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  date text not null,
  time text not null,
  location text not null,
  type text not null, -- 'Workshop', 'Contest', 'Talk'
  status text not null, -- 'upcoming', 'past'
  attendees integer default 0,
  max_attendees integer not null,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Enable RLS for events
alter table public.events enable row level security;

-- Policies for events
create policy "Anyone can view events"
  on public.events for select
  using (true);

-- Create internships table
create table public.internships (
  id integer generated by default as identity primary key,
  company text not null,
  role text not null,
  location text not null,
  mode text not null, -- 'Remote', 'On-site', 'Hybrid'
  stipend text not null,
  duration text not null,
  batch jsonb not null, -- array of strings e.g., '["2024", "2025"]'
  type text not null, -- 'SDE', 'Data', 'Web'
  posted text not null,
  deadline text not null,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Enable RLS for internships
alter table public.internships enable row level security;

-- Policies for internships
create policy "Anyone can view internships"
  on public.internships for select
  using (true);

-- Wait, what about creating/updating/deleting?
-- We can add policies for an admin or just rely on the server side / nextjs middleware to prevent non-admins from hitting the delete/create endpoints. Or we can just bypass RLS via service role, but since the frontend is likely using anon key, we should provide an admin policy if we use `auth.uid()`. But for now, we'll just disable RLS or allow insert/update/delete for authenticated admin users. Wait, the admin is based on email `vigneshwarvigneshwar292@gmail.com`.
-- We will just use the anon key since it seems safe for display, but for insert/delete via client, we need RLS if using anon key, or we can use `auth.uid()`. Let's create server actions to bypass RLS easily using the service role or normal client relying on the existing admin check.
-- Let's just create a policy allowing admin email:
create policy "Admin can insert events"
  on public.events for insert
  with check (auth.email() = 'vigneshwarvigneshwar292@gmail.com');

create policy "Admin can update events"
  on public.events for update
  using (auth.email() = 'vigneshwarvigneshwar292@gmail.com');

create policy "Admin can delete events"
  on public.events for delete
  using (auth.email() = 'vigneshwarvigneshwar292@gmail.com');

create policy "Admin can insert internships"
  on public.internships for insert
  with check (auth.email() = 'vigneshwarvigneshwar292@gmail.com');

create policy "Admin can update internships"
  on public.internships for update
  using (auth.email() = 'vigneshwarvigneshwar292@gmail.com');

create policy "Admin can delete internships"
  on public.internships for delete
  using (auth.email() = 'vigneshwarvigneshwar292@gmail.com');
